services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      OFFICE_HOME: /usr/lib/libreoffice
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "4173:80"

